### ISSUE TITLE
로그인한 사용자가 관리하는 회사 정보를 가져오려 하는데 현재의 연관관계로는 가져올 수 있는 방법이 없어 의견을 주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by bluedskim** [SEONGNAM-SELLDOK/CLONE-PROJECT#67]
로그인시 참조하는 회원정보 엔티티는 Employee 인데 이 엔티티는 Company와 연관관계가 없습니다.
반면 Member와  Company는 연관관계가 있습니다만 Member와 Employee는 연관관계가 없습니다
(아래 ERD를 참고해주세요)
![](https://i.ibb.co/5szktpR/Screenshot-from-2021-01-11-23-48-28.png)

제 생각에 둘 중의 한가지 방법을 선택해야 할 것 같습니다.

1. Employee 와 Company를 @OneToOne으로 연결
2. Employee 와 Member를 @OneToOne으로 연결 

혹은 다른 의견 있으시면 공유 부탁드립니다.

**Comment by Gogisung** [comment]
저는 1번으로 연관 관계를 설정 하는 것이 좋아 보입니다 @bluedskim
